<?php

require_once 'Pincrowd/Filter/EmailAddress.php';

/**
 * Test class for Pincrowd_Filter_EmailAddress.
 * Generated by PHPUnit on 2012-01-19 at 18:30:51.
 */
class Pincrowd_Filter_EmailAddressTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Pincrowd_Filter_EmailAddress
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Pincrowd_Filter_EmailAddress;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert (' email@domain.com ') == 'email@domain.com'.
     *
     * @covers Pincrowd_Filter_EmailAddress::filter
     */
    public function testFilter()
    {
        $this->assertEquals(
          'email@domain.com',
          $this->object->filter(' email@domain.com ')
        );
    }

    /**
     * Generated from @assert ('this is a test email@domain.com and no') == 'email@domain.com'.
     *
     * @covers Pincrowd_Filter_EmailAddress::filter
     */
    public function testFilter2()
    {
        $this->assertEquals(
          'email@domain.com',
          $this->object->filter('this is a test email@domain.com and no')
        );
    }

    /**
     * Generated from @assert ('"Test User<email@domain.com>"') == 'email@domain.com'.
     *
     * @covers Pincrowd_Filter_EmailAddress::filter
     */
    public function testFilter3()
    {
        $this->assertEquals(
          'email@domain.com',
          $this->object->filter('"Test User<email@domain.com>"')
        );
    }
}

