<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-25 at 13:12:39.
 * @group Game
 */
class Pincrowd_Model_Game_GameTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Pincrowd_Model_Game_Game
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Pincrowd_Model_Game_Game;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    /**
     * @return array
     */
    protected function gameProvider()
    {
        $data = array(
            array('throws' => array('x','x','x','x','x','x','x','x','x','x','x','x'), 'total' => 300)
        );
        return $data;
    }

    /**
     * @covers Pincrowd_Model_Game_Game::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pincrowd_Model_Game_Game::pushThrow
     * @todo   Implement testPushThrow().
     */
    public function testPushThrow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pincrowd_Model_Game_Game::calculateScore
     * @dataprovider gameProvider
     */
    public function testCalculateScore($data)
    {
        $game = new Pincrowd_Model_Game_Game($data);
        print_r($game->toArray());
    }

    /**
     * @covers Pincrowd_Model_Game_Game::setFilter
     * @todo   Implement testSetFilter().
     */
    public function testSetFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
