<?php

require_once 'Pincrowd/Filter/Html2Text.php';

/**
 * Test class for Pincrowd_Filter_Html2Text.
 * Generated by PHPUnit on 2012-01-19 at 18:31:15.
 */
class Pincrowd_Filter_Html2TextTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Pincrowd_Filter_Html2Text
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Pincrowd_Filter_Html2Text;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert ('<p>') == "\n\n\t".
     *
     * @covers Pincrowd_Filter_Html2Text::filter
     */
    public function testFilter()
    {
        $this->assertEquals(
          "\n\n\t",
          $this->object->filter('<p>')
        );
    }

    /**
     * Generated from @assert ('&reg;') == '(R)'.
     *
     * @covers Pincrowd_Filter_Html2Text::filter
     */
    public function testFilter2()
    {
        $this->assertEquals(
          '(R)',
          $this->object->filter('&reg;')
        );
    }
}

