<?php

require_once 'Pincrowd/Filter/PhoneNumber.php';

/**
 * Test class for Pincrowd_Filter_PhoneNumber.
 * Generated by PHPUnit on 2012-01-19 at 18:31:23.
 */
class Pincrowd_Filter_PhoneNumberTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Pincrowd_Filter_PhoneNumber
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Pincrowd_Filter_PhoneNumber;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert ('17735551212') == '7735551212'.
     *
     * @covers Pincrowd_Filter_PhoneNumber::filter
     */
    public function testFilter()
    {
        $this->assertEquals(
          '7735551212',
          $this->object->filter('17735551212')
        );
    }
}

